### ISSUE TITLE
SQLite => migration or flat files

### ISSUE THREAD

**Issue by deobald** [pariyatti/mobile-app#71]
## Tasks

* [x] decide on solution:
    * we'll use basic Drift migrations for now, and get rid of Drift+SQLite in a future release, in favour of looking up bookmarked items directly from the Dio cache
* [x] test and configure schema migration
* [x] add `_kosaURL` field to the `Cards` table so we can look them up from Dio in a future release: https://github.com/pariyatti/mobile-app/blob/master/lib/local_database/cards.dart
* [x] store `_kosaURL` in Shared Preferences instead of SQLite/Drift -- this has moved here: https://github.com/pariyatti/mobile-app/issues/83

---

Currently, SQLite does not have any data migration. Adding new entities requires the complete removal of the app and re-installation of the app to correct the generated database files.

## Option 1: Migration

Add a schema migration tool. This allows us to reuse the existing SQLite code, but it adds complexity.

## Option 2: Switch to NoSQL, kv, or flat files

Consider Hive?

* one entity per file
* flat only ; key-value pairs
* version/schema tracked per file

**Comment by deobald** [comment]
Should we consider Sqflite? https://medium.com/flutter-community/migrating-a-mobile-database-in-flutter-sqlite-44ac618e4897
